export default interface OrderAttribute {
    FirstName: String,
    LastName: String,
    _Street: String,
    _Apt: String,
    _City: String,
    _Zip: String,
    _Country: String,
    _State: String,
    DeliverTo: String,
    _Design: String,
    Font: String,
    Message: String,
    Delivery: String,
    DeliveryDate: String,
    isAccountPage: Boolean,
    lineItemId?: String,
}
