import { WIDGET_PREFIX } from './globals';

const styleClass = name => `${WIDGET_PREFIX}-${name}`;

export default {
  //Widget buttons
  WIDGET_INPUT_ROW: styleClass("widget-option-row"),
  WIDGET_INPUT_PRICE: styleClass("widget-option-price"),
  WIDGET_INPUT_TEXT: styleClass("widget-option-text"),

  //Inspiration Popup
  INSP_WRAPPER: styleClass("insp-wrapper"),
  INSP_WRAPPER_INNER: styleClass("insp-wrapper-inner"),
  INSP_TOP_BAR: styleClass("insp-wrapper-topbar"),
  INSP_TITLE: styleClass("insp-wrapper-title"),
  INSP_SUBTITLE: styleClass("insp-wrapper-subtitle"),
  INSP_FOOTER: styleClass("insp-wrapper-footer"),
  INSP_QUOTE_ITEM: styleClass("insp-wrapper-quote-item"),
  INSP_QUOTE_CONTAINER: styleClass("insp-wrapper-quote-container"),

  // Popup
  POPUP: styleClass('giftcard_generator'),
  POPUP_INNER_BACKDROP: styleClass('inner-backdrop'),
  POPUP_HEADER: styleClass('giftcard_generator-header'),
  POPUP_HEADER_TITLE: styleClass('giftcard_generator-header-title'),
  POPUP_CLOSE_BTN: styleClass('giftcard_generator-close'),
  POPUP_CLOSE_CONTAINER: styleClass('giftcard_generator-close-container'),
  POPUP_BODY: styleClass('giftcard_generator-body'),
  POPUP_BODY_WRAPPER: styleClass('giftcard_generator-body-wrapper'),
  POPUP_OPTIONS: styleClass('giftcard_generator-options'),
  POPUP_OPTIONS_DESIGNS: styleClass('giftcard_generator-options_design'),
  POPUP_OPTIONS_DESIGNS_MAIN: styleClass('giftcard_generator-options_design-main'),
  POPUP_PREVIEW_INPUT_ROW: styleClass('giftcard_generator-preview-input-row'),
  POPUP_PREVIEW_INPUT_LABEL: styleClass('giftcard_generator-preview-input-label'),
  POPUP_OPTIONS_DESIGNS_ITEM: styleClass('giftcard_generator-options_design-item'),
  POPUP_OPTIONS_DESIGNS_ITEM_CONTENT: styleClass('giftcard_generator-options_design-item-content'),
  POPUP_OPTIONS_FONTS: styleClass('giftcard_generator-fonts'),
  POPUP_OPTIONS_QUOTES: styleClass('giftcard_generator-quotes'),
  POPUP_OPTIONS_QUOTES_ITEM: styleClass('giftcard_generator_quotes-quotes'),
  POPUP_PREVIEW: styleClass('giftcard_generator-preview'),
  POPUP_PREVIEW_CONTAINER: styleClass('giftcard_generator-preview-container'),
  POPUP_PREVIEW_HEADING: styleClass('giftcard_generator-preview-heading'),
  POPUP_PREVIEW_TAB_MENU_CONTENT: styleClass('giftcard_generator-preview-tab-content'),
  POPUP_PREVIEW_TAB_MENU: styleClass('giftcard_generator-preview-tab-menu'),
  POPUP_PREVIEW_TAB_MENU_ITEM: styleClass('giftcard_generator-preview-tab-menu-item'),
  POPUP_PREVIEW_CARD_FRONT: styleClass('giftcard_generator-preview-card-front'),
  POPUP_PREVIEW_CARD_TEXT: styleClass('giftcard_generator-preview-card-text'),
  POPUP_PREVIEW_CARD_TEXT_CONTENT: styleClass('giftcard_generator-preview-card-text-content'),
  POPUP_PREVIEW_CARD_FRONT_IMAGE: 'gcw-front-image',
  POPUP_PREVIEW_CARD_BORDER: styleClass('giftcard_generator-preview-border'),
  POPUP_PREVIEW_FRONT: styleClass('giftcard_generator-preview-front'),
  POPUP_PREVIEW_BACK: styleClass('giftcard_generator-preview-back'),
  POPUP_PREVIEW_INSIDE: styleClass('giftcard_generator-preview-inside'),
  POPUP_FONT_PICKER: 'font-picker-gcw',
  POPUP_OPTIONS_TEXTAREA: styleClass('giftcard_generator-options-textarea'),
  POPUP_OPTIONS_TEXTAREA_ERROR: styleClass('giftcard_generator-options-textarea-error'),
  POPUP_OPTIONS_LINES: styleClass('giftcard_generator-options-lines'),
  POPUP_OPTIONS_EMOJI: styleClass('giftcard_generator-emojiimg'),

  POPUP_FINAL_PREVIEW: styleClass('giftcard_generator-final-preview'),
  POPUP_FINAL_PREVIEW_TITLE: styleClass('giftcard_generator-final-preview-title'),
  POPUP_FINAL_PREVIEW_CONTAINER: styleClass('giftcard_generator-final-preview-container'),
  POPUP_FINAL_PREVIEW_FRONT_WRAPPER: styleClass('giftcard_generator-final-preview-front-wrapper'),
  POPUP_FINAL_PREVIEW_CARD_FRONT: styleClass('giftcard_generator-final-preview-card-front'),
  POPUP_FINAL_PREVIEW_CARD_TEXT: styleClass('giftcard_generator-final-preview-card-text'),
  POPUP_FINAL_PREVIEW_CARD_TEXT_CONTENT: styleClass('giftcard_generator-final-preview-card-text-content'),

  BUTTON: styleClass('btn'),
  PRIMARY_BUTTON: styleClass('primary-button'),
  SECONDARY_BUTTON: styleClass('secondary-button'),
  MAIN_TAB_BUTTON: styleClass('main-tab-button'),
  SIMPLE_BUTTON: styleClass('simple-button'),
  BUTTON_CONTAINER: styleClass('button-container'),
  BACK_BUTTON: styleClass('back-button'),
  EDIT_BUTTON: styleClass('edit-button'),

  POPUP_LOGO: styleClass('popup-logo'),
  POPUP_TITLE: styleClass('popup-title'),
  POPUP_SUBTITLE: styleClass('popup-subTitle'),
  POPUP_SUBTEXT: styleClass('popup-subText'),
  POPUP_SUBBTNTEXT: styleClass('popup-subBtnText'),
  POPUP_FOOTER_IMAGE: styleClass('popup-footerBg'),
  POPUP_HEADER_IMAGE: styleClass('popup-headerBg'),

  POPUP_DELIVERY_FORM: styleClass('popup-delivery-form'),
  POPUP_FORM_INPUT_GROUP: styleClass('popup-input-group'),
  POPUP_FORM_BUTTON_GROUP: styleClass('popup-button-group'),
  POPUP_FORM_INPUT_RADIO_GROUP: styleClass('popup-input-radio-group'),
  POPUP_FORM_INPUT_ROW: styleClass('popup-input-row'),
  POPUP_FORM_INPUT: styleClass('popup-form-input'),
  POPUP_FORM_INPUT_RADIO: styleClass('popup-form-input-radio'),
  POPUP_FORM_LABEL: styleClass('popup-form-label'),
  POPUP_FORM_LABEL_RADIO: styleClass('popup-form-label-radio'),
  POPUP_FORM_INPUT_GROUP_APPEND: styleClass('popup-input-group-append'),
  POPUP_FORM_CONTROL: styleClass('popup-form-control'),
  POPUP_FORM_ERRORS: styleClass('popup-form-errors'),
  POPUP_FORM_BTN: styleClass('popup-btn'),
  POPUP_FORM_BTN_SUBMIT: styleClass('popup-btn-submit'),
  POPUP_FOOTER: styleClass('popup-footer'),
  POPUP_PRIVACY_POLICY: styleClass('popup-privacy-policy'),
  // General
  TITLE_H3: styleClass('title-h3'),
  BODY_TEXT: styleClass('body-text'),
  // Positions
  POSITION_TOP_LEFT: styleClass('position-top-left'),
  POSITION_TOP_CENTER: styleClass('position-top-center'),
  POSITION_TOP_RIGHT: styleClass('position-top-right'),
  POSITION_BOTTOM_LEFT: styleClass('position-bottom-left'),
  POSITION_BOTTOM_CENTER: styleClass('position-bottom-center'),
  POSITION_BOTTOM_RIGHT: styleClass('position-bottom-right'),
  // Popup Button
  TOGGLE_BUTTON: styleClass('btn-toggle'),
  // Backdrop
  BACKDROP: styleClass('backdrop'),
  // Preloader
  PRELOADER: styleClass('preloader'),
  // Notification
  NOTIFICATION: styleClass('notification'),
  NOTIFICATION_BODY: styleClass('notification-body'),
  NOTIFICATION_TITLE: styleClass('notification-title'),
  NOTIFICATION_MESSAGE: styleClass('notification-message'),
  // Status
  ACTIVE: 'active',
  DISABLED: 'disabled',
  DISPLAY_BLOCK: styleClass('d-block'),
  DISPLAY_FLEX: styleClass('d-flex'),
  DISPLAY_NONE: styleClass('d-none'),
  JUSTIFY_CENTER: styleClass('justify-center'),
  JUSTIFY_BETWEEN: styleClass('justify-between'),
  JUSTIFY_END: styleClass('justify-end'),
  VISSABILITY_HIDDEN: styleClass('visibility-hidden'),
  VISSABILITY_VISSIBLE: styleClass('visibility-visible'),
  // Grid
  CONTAINER:styleClass('container'),
  ROW:styleClass('row'),
  COL_3:styleClass('col-3'),
  COL_4:styleClass('col-4'),
  COL_6:styleClass('col-6'),
  COL_8:styleClass('col-8'),
  // Animations
  ANIMATED: styleClass('animated'),
  ANIMATION_FADE_IN: styleClass('fadeIn'),
  ANIMATION_FADE_IN_UP: styleClass('fadeInUp'),
  ANIMATION_FADE_IN_DOWN: styleClass('fadeInDown'),
  ANIMATION_FADE_OUT: styleClass('fadeOut'),
  ANIMATION_FADE_OUT_UP: styleClass('fadeOutUp'),
  ANIMATION_FADE_OUT_DOWN: styleClass('fadeOutDown'),


  // warning Popup
  WARNINGPOPUP: styleClass('giftcard_warning_generator'),
  WARNINGPOPUP_INNER_BACKDROP: styleClass('inner-backdrop'),
  WARNINGPOPUP_HEADER: styleClass('giftcard_warning_generator-header'),
  WARNINGPOPUP_HEADER_TITLE: styleClass('giftcard_warning_generator-header-title'),
  WARNINGPOPUP_CLOSE_BTN: styleClass('giftcard_warning_generator-close'),
  WARNINGPOPUP_CLOSE_CONTAINER: styleClass('giftcard_warning_generator-close-container'),
  WARNINGPOPUP_BODY: styleClass('giftcard_warning_generator-body'),
  WARNINGPOPUP_BODY_WRAPPER: styleClass('giftcard_warning_generator-body-wrapper'),
  WARNINGPOPUP_BUTTON_CONTAINER:styleClass('giftcard_warning_generator-button-container'),

  // warning child exist Popup
  WARNINGCHILDPOPUP: styleClass('giftcard_warning_child_generator'),
  WARNINGPOPUP_INNER_BACKDROP: styleClass('inner-backdrop'),
  WARNINGPOPUP_HEADER: styleClass('giftcard_warning_generator-header'),
  WARNINGPOPUP_HEADER_TITLE: styleClass('giftcard_warning_generator-header-title'),
  WARNINGPOPUP_CLOSE_BTN: styleClass('giftcard_warning_generator-close'),
  WARNINGPOPUP_CLOSE_CONTAINER: styleClass('giftcard_warning_generator-close-container'),
  WARNINGPOPUP_BODY: styleClass('giftcard_warning_generator-body'),
  WARNINGPOPUP_BODY_WRAPPER: styleClass('giftcard_warning_generator-body-wrapper'),
  WARNINGPOPUP_BUTTON_CONTAINER:styleClass('giftcard_warning_generator-button-container')
};
